### ISSUE TITLE
VS2013 Cant Create Solution

### ISSUE THREAD

**Issue by eidam15** [Joshua-Ashton/Source-PlusPlus#10]
Im just unable to create the solution at all. Is it only me ?

*ERROR: Unable to find RegKey for .vcproj or .vcxproj files in solutions.*

**Comment by Joshua-Ashton** [comment]
VS 2013 isn't supported. Use VS 2015

**Comment by eidam15** [comment]
To be honest i tried both 2013 and 2015 and i still get the same error when creating a solution.
