### ISSUE TITLE
Solution Not Creating.

### ISSUE THREAD

**Issue by eidam15** [Joshua-Ashton/Source-PlusPlus#13]
Trying VS2013, VS2015 And even VS2012 and getting the same exact error is just hilarious i probably. Getting kinda lost in this one. If somebody could explain how to create solution for vs2015 that would be great.

**Comment by Joshua-Ashton** [comment]
Yeah but what actually is the error?

**Comment by eidam15** [comment]
Still unable to find regkeys for vcproj and vcxproj files... But other source builds generate solution just fine.
I just want to use the new features you implemented.

**Comment by Joshua-Ashton** [comment]
Run VS14.reg

**Comment by eidam15** [comment]
Kinda confused here. Where im supposed to find this file ? Thanks.

**Comment by Joshua-Ashton** [comment]
Its in src
