### ISSUE TITLE
I can't compile this project

### ISSUE THREAD

**Issue by GodLeaveMe** [Joshua-Ashton/Source-PlusPlus#24]
I can't compile this project with VS2019/2017/2015/2013/2012/2010
I've tried almost all the supported VS versions
But none of them can be compiled.
The screenshots are as follows:
![image](https://user-images.githubusercontent.com/45651732/50822877-b923b980-136d-11e9-8ae2-e366c412d278.png)

**Comment by GodLeaveMe** [comment]
@Joshua-Ashton @SCell555 @Gocnak

**Comment by Gocnak** [comment]
Gonna learn Chinese real quick, I'll get back to you in ~10 years so I can read those error messages

**Comment by Gocnak** [comment]
In seriousness, looks like a some sort of C++ STL issues, but if you've tried every VS version, I wouldn't know.

**Comment by SCell555** [comment]
Looks like compiler is not set to C++14 mode, those functions are marked as constexpr, that's why it errors out. Try replacing line `$AdditionalOptions	"$BASE /Zc:inline" //[$VS2013]` with `$AdditionalOptions	"$BASE /Zc:inline /std:c++14" //[$VS2013]` in **source_win32_base.vpc** and regenerate project, so that all projects have `/std:c++14` switch.

**Comment by GodLeaveMe** [comment]
> Looks like compiler is not set to C++14 mode, those functions are marked as constexpr, that's why it errors out. Try replacing line `$AdditionalOptions	"$BASE /Zc:inline" //[$VS2013]` with `$AdditionalOptions	"$BASE /Zc:inline /std:c++14" //[$VS2013]` in **source_win32_base.vpc** and regenerate project, so that all projects have `/std:c++14` switch. I thought that I set that when I did upgrade to vs2017.
> 
> Or it might be something completely different, some issue with headers, since it can't figure out some types.

Should I install VS2013 back? Because I uninstalled it before

**Comment by GodLeaveMe** [comment]
> > Looks like compiler is not set to C++14 mode, those functions are marked as constexpr, that's why it errors out. Try replacing line `$AdditionalOptions	"$BASE /Zc:inline" //[$VS2013]` with `$AdditionalOptions	"$BASE /Zc:inline /std:c++14" //[$VS2013]` in **source_win32_base.vpc** and regenerate project, so that all projects have `/std:c++14` switch. I thought that I set that when I did upgrade to vs2017.
> > Or it might be something completely different, some issue with headers, since it can't figure out some types.
> 
> Should I install VS2013 back? Because I uninstalled it before



> Looks like compiler is not set to C++14 mode, those functions are marked as constexpr, that's why it errors out. Try replacing line `$AdditionalOptions	"$BASE /Zc:inline" //[$VS2013]` with `$AdditionalOptions	"$BASE /Zc:inline /std:c++14" //[$VS2013]` in **source_win32_base.vpc** and regenerate project, so that all projects have `/std:c++14` switch. I thought that I set that when I did upgrade to vs2017.
> 
> Or it might be something completely different, some issue with headers, since it can't figure out some types.

I currently have two versions installed, 2019 preview and 2010

**Comment by SCell555** [comment]
Only vs2015+ supports C++14, and vs2017+ has full support for it

**Comment by GodLeaveMe** [comment]
> Only vs2015+ supports C++14, and vs2017+ has full support for it

And 2019 has full support too?

**Comment by SCell555** [comment]
yes

**Comment by GodLeaveMe** [comment]
> yes

I've done what you said, but it still shows mistakes
For example:

Error (Activity) E1696 Could not open source file "balabalabala.h"

Also

Error (activity) E0020 undefined identifier "balabalabala"

Also

Error (activity) E0070 does not allow incomplete types

Also

Error (Activity) E0282 There is no "balabalabala" in the global scope

Also

Warning C4819 This file contains characters that cannot be represented in the current code page (936). Save this file in Unicode format to prevent data loss (compile source file KeyValues. cpp) Tier1

And so on.

Specific errors in compressed video

You can open it and have a look.

I'm sorry to trouble you.

thank you!

[2019-01-08 22-37-42.zip](https://github.com/Joshua-Ashton/Source-PlusPlus/files/2737179/2019-01-08.22-37-42.zip)

**Comment by GodLeaveMe** [comment]
> In seriousness, looks like a some sort of C++ STL issues, but if you've tried every VS version, I wouldn't know.

thank you

**Comment by ZeVoidah** [comment]
same problem here

**Comment by GodLeaveMe** [comment]
> same problem here

Did you solve this problem?

**Comment by GodLeaveMe** [comment]
> @SCell555 I hope you can help me compile the required files, because I really need CSM to add quality to my project.

I have a project of my own, but users feel that the quality of the game is not good enough, they can not be satisfied with SHADER ENB, so I think your project is the best choice.
